# Railway Configuration for Balloon Pump Relayer Service
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[env]
NODE_ENV = "production"
PORT = "3001"

# Service configuration
[services.relayer]
source = "."

